/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Railreservation.Trainreservation;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Traininformation.Traininfo;
import javax.swing.JOptionPane;

/**
 *
 * @author irudr
 */
public class AddTrain extends javax.swing.JFrame {
    public Traininfo temptrain;
    /**
     * Creates new form AddTrain
     */
    public AddTrain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTrainNoAddTrain = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTrainNameAddTrain = new javax.swing.JTextField();
        txtStartPointAddTrain = new javax.swing.JTextField();
        txtEndPointAddTrain = new javax.swing.JTextField();
        AddtrainSubmit = new javax.swing.JButton();
        AddTrainBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        RmtrainAction = new javax.swing.JButton();
        rmtrain = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TrainNo", "Train Name", "Start Point", "End Point"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Train No");

        txtTrainNoAddTrain.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Train Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Start Point");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("End Point");

        txtTrainNameAddTrain.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        txtStartPointAddTrain.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        txtEndPointAddTrain.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        AddtrainSubmit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AddtrainSubmit.setText("Add Train");
        AddtrainSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddtrainSubmitActionPerformed(evt);
            }
        });

        AddTrainBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AddTrainBack.setText("Back");
        AddTrainBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTrainBackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Bhubaneswar Metro");

        RmtrainAction.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RmtrainAction.setText("Removetrain");
        RmtrainAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RmtrainActionActionPerformed(evt);
            }
        });

        rmtrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmtrainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTrainNoAddTrain)
                    .addComponent(txtTrainNameAddTrain)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStartPointAddTrain)
                    .addComponent(txtEndPointAddTrain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AddtrainSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddTrainBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(rmtrain, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(RmtrainAction, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTrainNoAddTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTrainNameAddTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtStartPointAddTrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtEndPointAddTrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddtrainSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddTrainBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rmtrain, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(RmtrainAction, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void AddTrainBackActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        AdminInterface Admininter=new AdminInterface();
        Admininter.setVisible(true);
        this.dispose();
    }                                            

    private void AddtrainSubmitActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        if(txtTrainNoAddTrain.getText().equals("")&&txtTrainNameAddTrain.getText().equals("")&&txtStartPointAddTrain.getText().equals("")&&txtEndPointAddTrain.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Blank Not Allowed");
        }else{
            String trainNoStr = txtTrainNoAddTrain.getText();
            int trainNumber = 0; // Default value if parsing fails
            try {
                trainNumber = Integer.parseInt(trainNoStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Train number should be a valid integer!");
                return; // Exit the method if parsing fails
            }
            temptrain=new Traininfo(trainNumber,txtTrainNameAddTrain.getText(),txtStartPointAddTrain.getText(),txtEndPointAddTrain.getText());
            Trainreservation trainreserv=Trainreservation.getInstance();
            trainreserv.addtrain(temptrain);
            addTrainManually(temptrain);
            AddStation addstation=new AddStation();
            addstation.fetchData(temptrain);
            addstation.setVisible(true);
            this.dispose();
        }
    }                                              
    private void rmtrainActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void RmtrainActionActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
            String trainNoStr = rmtrain.getText();

        if (trainNoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the Train No to remove.");
            return;
        }

        try {
            int trainNumberToRemove = Integer.parseInt(trainNoStr);
            Traininfo trainToRemove = null;
            for (Traininfo train : Trainreservation.getInstance().Trains) {
                if (train.trainnumber == trainNumberToRemove) {
                    trainToRemove = train;
                    break;
                }
            }
            if (trainToRemove != null) {
                Trainreservation.getInstance().Trains.remove(trainToRemove);
                updateTable();
                this.dispose();
                AddTrain addtrain=new AddTrain();
                addtrain.fetchData();
                addtrain.setVisible(true);
                JOptionPane.showMessageDialog(this, "Train removed successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Train with Train No. " + trainNumberToRemove + " not found.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Train No.");
        }
    }                                             
    private void updateTable() {
    fetchData();
    }
    /**
     * @param args the command line arguments
     */
    public void fetchData(){
        Trainreservation trainreserv=Trainreservation.getInstance();
        List<Traininfo> trainList = trainreserv.Trains; // Assuming Trains is a list of Train objects
        populate(trainList);
    }
    public void populate(List<Traininfo> trainList) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear the table before populating

        for (Traininfo train : trainList) {
            Object[] rowData = {
                train.trainnumber,
                train.trainname,
                train.sourseStation,
                train.destitionStation
            };
            model.addRow(rowData); 
        }
    }
    public void addTrainManually(Traininfo newTrain) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] rowData = {
            newTrain.trainnumber,
            newTrain.trainname,
            newTrain.sourseStation,
            newTrain.destitionStation
        };
        model.addRow(rowData); 
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTrain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AddTrainBack;
    private javax.swing.JButton AddtrainSubmit;
    private javax.swing.JButton RmtrainAction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField rmtrain;
    private javax.swing.JTextField txtEndPointAddTrain;
    private javax.swing.JTextField txtStartPointAddTrain;
    private javax.swing.JTextField txtTrainNameAddTrain;
    private javax.swing.JTextField txtTrainNoAddTrain;
    // End of variables declaration                   

}
